### ISSUE TITLE
tokenize 野球 by Kuromoji.js and Kuromoji.java

### ISSUE THREAD

**Issue by iapyeh** [hexenq/kuroshiro#11]
At beginning, I got this:
![image](https://cloud.githubusercontent.com/assets/4695577/26816807/2e5e0bb4-4ac6-11e7-809e-dfb99ef474f3.png)
Then I went to kuromoji.js ( http://takuyaa.github.io/kuromoji.js/demo/tokenize.html ), also got the same tokens, 
![image](https://cloud.githubusercontent.com/assets/4695577/26816851/5fdb97ce-4ac6-11e7-8b4b-1f1cf8544e4b.png)
But another kuromoji.java ( http://atilika.org/kuromoji/ ), gives the correct tokens:
![image](https://cloud.githubusercontent.com/assets/4695577/26816922/cbc417cc-4ac6-11e7-9d38-827843759730.png)

It seems that there are two kinds of Kuromoji and they are different.

**Comment by hexenq** [comment]
Hello, iapyeh. As I see it, [takuyaa/kuromoji.js](https://github.com/takuyaa/kuromoji.js) is a partial javascript implementation of [atilika/kuromoji](https://github.com/atilika/kuromoji). atilika/kuromoji supports more types of dictionaries. Besides, it's up to users to choose the adequate dictionary to meet their tokenization requirements. The problem you come across maybe has more relations with the dictionary you use,

**Comment by andy840119** [comment]
it seems that is kuromoji's problem (i am not sure is it a bug)
like 一人（ひとり,hitori）will be separate as two words 一(いち,ichi) 人（ひと,hito）

**Comment by hexenq** [comment]
Actually, the result is based on what dictionary kuromoji used. Kuromoji is just a morphological analyzer. In the under-developing 1.x version of kuroshiro, you will be able to choose what morphological analyzer you prefer to use as same as the dictionary.

**Comment by hexenq** [comment]
kuroshiro has been updated to version 1.0.0-rc.1, which supports various morphological analyzers. Have a try.😋
