### ISSUE TITLE
[Suggestion] Use promises instead of callbacks

### ISSUE THREAD

**Issue by mornir** [hexenq/kuroshiro#29]
Hi!
I find promises more pleasant to work with. Also it would allow us to write code like that:
```js
await kuroshiro.init();
const result = kuroshiro.convert('感じ取れたら手を繋ごう！');   
console.log(result);
```
:smiley:

**Comment by hexenq** [comment]
New version of kuroshiro is released, which utilizes async/await function. Have a look. 😉

**Comment by retorquere** [comment]
I'm trying to figure out the new release, but there's a few things that are unclear to me:

1. where does `KuromojiAnalyzer` come from? Do I get that using `import * as KuromojiAnalyzer from "kuroshiro-analyzer-kuromoji"`?
3. `const result = await kuroshiro.convert("感じ取れたら手を繋ごう、重なるのは人生のライン and レミリア最高！", { to: "hiragana" })` suggests that kuroshiro.convert returns a promise, but `const result = kuroshiro.convert('感じ取れたら手を繋ごう、重なるのは人生のライン and レミリア最高！')` in the webpack example suggests it returns a results, not a promise for a result. Is there still a synchronous convert? My code depends on the convert being synchronous.

**Comment by retorquere** [comment]
Oh and shouldn't `import * as Kuroshiro from "kuroshiro"` be `import Kuroshiro from "kuroshiro"`?

**Comment by hexenq** [comment]
Hello, @retorquere . The documents was quite confusing. I have update them and release a new RC version 1.0.0-rc.2. Thank you very much and feel free to contact me if you have other questions.

**Comment by retorquere** [comment]
It's clear now, but why has convert gone from sync to async? Is there still a sync version? I call convert from a place where I cannot use async.

**Comment by retorquere** [comment]
It's clear now, but why has convert gone from sync to saync? Is there still a sync version? I call convert from a place where I cannot use async.

**Comment by hexenq** [comment]
`convert` gone from sync to async because not all the analyzers support sync analysis. If you cannot use async/await function, you cloud use Promise instead to make code work like sync. Or if it's possible, could you describe the situation where you cannot use async.

**Comment by retorquere** [comment]
Promises are still async.

I call kuroshiro in a parser built using pegjs. Kuroshiro is being called in a longer chain of sync calls and I can't easily change that.

**Comment by hexenq** [comment]
pegjs seems not support async. I found [abbr/deasync](https://github.com/abbr/deasync) might be helpful for you but I haven't not yet used it.  Have a look.

**Comment by retorquere** [comment]
The generated parser in my case doesn't, and deasync doesn't work in my environment (Firefox extension). I understand why you're moving to async, I had just hoped that the kuromoji/kuroshiro could still work sync. I'll just stay on the older version for now.
