### ISSUE TITLE
kuroshiro-analyzer-yahoo-webapi no longer work as YQL is dead

### ISSUE THREAD

**Issue by vincentlaucy** [hexenq/kuroshiro#57]
current lib relies on YQL.
the furigana api endpoint itself is live while it seems `output=json` not working
`http://jlp.yahooapis.jp/FuriganaService/V1/furigana?appId=${appId}&sentence=${sentence}&output=json`

**Comment by hexenq** [comment]
Hello, Vincent. I have removed the dependence of `kuroshiro-analyzer-yahoo-webapi` on YQL and published a new version. Thank you for reminding me.
