### ISSUE TITLE
wrong result when convert to furigana

### ISSUE THREAD

**Issue by cj1128** [hexenq/kuroshiro#60]
I am trying to convert `渡り鳥` using code bellow:

```javascript
const Kuroshiro = require("kuroshiro")
const a = require("kuroshiro-analyzer-kuromoji")
const kuroshiro = new Kuroshiro()
;(async () => {
  await kuroshiro.init(new a())
  const str = "渡り鳥"
  const res = await kuroshiro.convert(str, {mode:"furigana", to:"hiragana"});
  console.log(res)
})()
```

And get the result

```txt
<ruby>渡<rp>(</rp><rt>わたりど</rt><rp>)</rp></ruby>り<ruby>鳥<rp>(</rp><rt></rt><rp>)</rp></ruby>
```

which is wrong, the correct result should be

```
<ruby>渡<rp>(</rp><rt>わた</rt><rp>)</rp></ruby>り<ruby>鳥<rp>(</rp><rt>どり</rt><rp>)</rp></ruby>
```

BTW, the async api is a real pain, we should make it sync, at least when used with kuromoji analyzer.

**Comment by halfsprit** [comment]
异步模式太糟糕，至少初始化时应该是同步模式，初始化是耗时的步骤，不应该每次计算时又初始化一次。

**Comment by fate-lovely** [comment]
@halfsprit 这个库接口设计为异步是有原因的，因为部分 analyzer 是异步的。当然，这个设计不太好，因为存在异步 analyzer，导致所有接口都异步了 = = 初始化并不存在什么问题吧，因为可以只初始化一次的。

**Comment by halfsprit** [comment]
analyzer 里面似乎也只有readFile是异步的，但是readFile好像也有同步版本，是不是使用readFile的同步版本就能解决这个问题呢？

**Comment by fate-lovely** [comment]
@halfsprit 和 `readFile` 关系不大，有部分 analyzer 是基于 web api 的，必须异步，比如 *kuroshiro-analyzer-yahoo-webapi*。

**Comment by halfsprit** [comment]
利用kuroshiro的库，编写了一个小工具，除了初始化要点时间外，后面就是即时进行转换。
链接：https://pan.baidu.com/s/1VMZQlCvR3jCq-0JSC04R7A 
提取码：rvga 
![sshot-1](https://user-images.githubusercontent.com/35736247/54867989-801eb100-4dc2-11e9-9fb1-f0630aea186c.png)

**Comment by KristerV** [comment]
as a non-japanese speaker i'd love to know what the verdict is (is the hiragana accurate or not) :)
