### ISSUE TITLE
微笑み converted to "bi emi" instead of "hohoemi"

### ISSUE THREAD

**Issue by louy2** [hexenq/kuroshiro#62]
微笑み is broken down to 微 and 笑み, and the resulting romaji becomes "bi emi", when it should be "hohoemi". This seems to be a limitation of kuromoji so I also opened a issue there.

https://github.com/takuyaa/kuromoji.js/issues/36

**Comment by louy2** [comment]
Yahoo-WebAPI seems to not have this issue, but we might want to customize dictionary, so it's best if we can continue using kuromoji.

**Comment by hexenq** [comment]
Thanks for your feedback. It's quite like what you said. It's up to you to choose the adequate dictionary to meet your tokenization and pronunciation requirements (#11). However kuromoji.js has its limitation on choosing dictionary. At this time, kuroshiro will not change the result of those morphological analyzers. But we could think of a solution for getting better results. You're welcome to raise a new issue if you have any ideas or suggestions. Closed.
