### ISSUE TITLE
TypeError: Kuroshiro is not a constructor

### ISSUE THREAD

**Issue by Tenpi** [hexenq/kuroshiro#66]
I get this error using both import and require statements. I have tried reinstalling the package but it does not work. 

Import:
import Kuroshiro from "kuroshiro";
const kuroshiro = new Kuroshiro();

Require:
const {Kuroshiro} = require("kuroshiro");
const kuroshiro = new Kuroshiro();

**Comment by Tenpi** [comment]
I fixed this issue, nvm.

**Comment by danghuudat** [comment]
how can you fix it?

**Comment by univeous** [comment]
@danghuudat I have the same issue, and it works fine when I changed to use kuroshiro 1.1.2 version.

**Comment by hw4n** [comment]
I can confirm @univeous' solution works.

in ``package.json``, mine looked like the following:
``"kuroshiro": "^1.1.2",``

however ``yarn install`` installed kuroshiro version 1.1.0, and the error was there

so changing that line to the following fixed the problem (replace caret with tilde)
``"kuroshiro": "~1.1.2",``

**Comment by MegumiKatou02** [comment]
`"kuroshiro": "~1.1.2"` replace caret with tilde then `npm install` or `yarn install`. I fixed this issue 👍

**Comment by madfcat** [comment]
Still an issue with ES6 and 1.2.0
