### ISSUE TITLE
Dictionary size

### ISSUE THREAD

**Issue by gonzales-gerald** [hexenq/kuroshiro#70]
Hi,

I would like to know if it is possible to load only the files required for Kanji to Katakana. Our problem is that the translation files are too big too load on first navigate of our application.

**Comment by hexenq** [comment]
Hello there. It would be slow on bootstrap when you use Kuromoji Analyzer. Actually, Kanji to Katakana or Kanji to Romaji doesn't make such big difference. It's the process of tokenization that costs the most which relies on big dict files, and this process is fundamental.

I suggest you have a look at the [mecab](https://github.com/hexenq/kuroshiro-analyzer-mecab) or [yahoo-api](https://github.com/hexenq/kuroshiro-analyzer-yahoo-webapi) analyzer. Both of them would save front-end loading time by handing over the workload to back-end server. You could consider using them instead if it's possible for your situation.

**Comment by gonzales-gerald** [comment]
Hello! Yes, now I understand that it is not a one-to-one conversion so this dictionaries are needed. Thank you for the suggestions, I will take a look at them!

**Comment by gonzales-gerald** [comment]
For the https://kuroshiro.org/#demo, I believe you are using an API version?

**Comment by hexenq** [comment]
Hello Gonzales. You're right. The mecab dictionary and kuroshiro both should be deployed on a server-end which exposes an API interface to your front-end. And I think the [mecab-ipadic-neologd](https://github.com/neologd/mecab-ipadic-neologd) would be a good choice for you. 

The demo page is using server-side kuroshiro with Yahoo-WebAPI analyzer plugin.

**Comment by gonzales-gerald** [comment]
Hi! We ended up using [Express](https://expressjs.com/) to run the translator as a separate service. We do an api call to that service so it the front-end application doesn't need to bootstrap the kuroshiro.

Thank you for your help!
