### ISSUE TITLE
[TS] Could not find a declaration file for module 'kuroshiro'.

### ISSUE THREAD

**Issue by hykilpikonna** [hexenq/kuroshiro#79]
On the official npm page, it says that TypeScript is supported:

![image](https://user-images.githubusercontent.com/22280294/110500494-41758480-80c7-11eb-9525-262b506a18d8.png)

But when I copy the import statement into my project, it prompted that there are no type declarations for the library, and the package `@types/kuroshiro` doesn't exist.

When I checked the source code, it does appear that there are no type declarations. Did I miss something?

![image](https://user-images.githubusercontent.com/22280294/110500757-8994a700-80c7-11eb-875d-2d6e997fa0a7.png)

**Comment by Rhodanthe1116** [comment]
The document you look on the npm page may be version < 1.
The typescript definitions are no longer available. 
See #48

**Comment by hykilpikonna** [comment]
> The document you look on the npm page may be version < 1.
> The typescript definitions are no longer available.
> See #48

Thanks for the info!
