### ISSUE TITLE
Error when call API (https://api.kuroshiro.org) - Error 1016

### ISSUE THREAD

**Issue by HieuND0711** [hexenq/kuroshiro#81]
Hi team,
I'm using your API for my project,
But recent days, when I call your API, I got this issue,
Could you help me to fix it?
Thanks!

![image](https://user-images.githubusercontent.com/3146236/120154399-08f2cc00-c21a-11eb-86d8-e06be1e48886.png)

`

Error 1016 Ray ID: 657e5b95c9802308 • 2021-05-31 07:06:07 UTC
Origin DNS error
What happened?
You've requested a page on a website (api.kuroshiro.org) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (api.kuroshiro.org).

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Check your DNS settings. If you are using a CNAME origin record, make sure it is valid and resolvable. Additional troubleshooting information here.
`

**Comment by hexenq** [comment]
Hello, It'll be ok now. Please note that the API on kuroshiro.org is only for test use.

**Comment by HieuND0711** [comment]
@hexenq thanks, bro.
It works fine now.
Thanks for your hard work.
